---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: busybox
    tag: 'latest'

inputs:
  - name: scdf-stream-demo

outputs:
  - name: build-output

run:
  path: scdf-stream-demo/pipelines/tasks/build.sh
